=== turquoisehealth/provider-price-transparency-guide/schemas/standardcharges/standardcharges.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "standardcharges": {
      "type": "object",
      "properties": {
        "description": { "type": "string" },
        "billing_code_type": { "enum": [ "CPT", "HCPCS", "ICD", "DRG" ] },
        "billing_code_type_version": { "type": "string" },
        "billing_code": { "type": "string" },
        "billing_code_modifier": { "type": "string" },
        "billing_class": { "enum": [ "facility", "professional" ] },
        "account_base_class": { "enum": [ "inpatient", "outpatient", "emergency" ] },
        "revenue_code": { "type": "number" },
        "ndc": { "type": "string" },
        "gross_charge": { "type": "number" },
        "cash_rate": { "type": "number" },
        "minimum_negotiated_rate": { "type": "number" },
        "maximum_negotiated_rate": { "type": "number" },

        "negotiated_rates": {
          "type": "array",
          "items": { "$ref": "#/definitions/negotiated_rate" },
          "default": []
        }
      },
      "required": ["description", "billing_class", "account_base_class", "gross_charge", "cash_rate", "minimum_negotiated_rate", "maximum_negotiated_rate"]
    },

    "negotiated_rate": {
      "type": "object",
      "properties": {
        "payer_name": { "type": "string" },
        "plan_name": { "type": "string" },
        "negotiated_rate": { "type": "number" },
        "expiration_date": { "type": "string", "format": "date" }
      },
      "required": [ "payer_name", "plan_name", "negotiated_rate" ]
    }
  },


  "type": "object",

  "properties": {
    "reporting_entity_name": { "type": "string" },
    "reporting_entity_medicare_id": { "type": "string" },
    "last_update_on": { "type": "string", "format": "date" },
    "standardcharges": {
      "type": "array",
      "items": { "$ref": "#/definitions/standardcharges" },
      "default": []
    }
  },
  "required": ["reporting_entity_name", "reporting_entity_medicare_id", "last_update_on", "standardcharges"]

}

=== turquoisehealth/provider-price-transparency-guide/examples/standardcharges/standardcharges-sample-ancillary_charges.json
{
  "reporting_entity_name": "St. Bonaventure Hospital",
  "reporting_entity_medicare_id": "123456",
  "last_update_on": "2020-01-01",
  "standardcharges": [
    {
      "description": "Arthroplasty, knee condyle and plateau, medial and lateral compartments",
      "billing_code_type": "CPT",
      "billing_code_type_version": "2020",
      "billing_code": "27447",
      "billing_code_modifier": "LT",
      "billing_class": "facility",
      "account_base_class": "outpatient",
      "revenue_code": 360,
      "gross_charge": 500.0,
      "cash_rate": 221.11,
      "minimum_negotiated_rate": 220.45,
      "maximum_negotiated_rate": 223.45,
      "negotiated_rates": [
        {
          "payer_name": "Insurance West",
          "plan_name": "Insurance West PPO",
          "negotiated_rate": 223.45,
          "expiration_date": "2022-01-01",
          "rate_inclusive_of_ancillary_charges": true
        },
        {
          "payer_name": "Insurance West",
          "plan_name": "Insurance West HMO",
          "negotiated_rate": 220.45,
          "expiration_date": "2022-01-01",
          "rate_inclusive_of_ancillary_charges": true
        }
      ],
      "ancillary_charges": [
        {
          "description": "Anesthesia for Arthroplasty",
          "billing_class": "facility",
          "revenue_code": 360,
          "gross_charge": 300.0
        },
        {
          "description": "Tools for Arthroplasty",
          "billing_class": "facility",
          "revenue_code": 360,
          "gross_charge": 100.0
        }
      ]
    }
  ]
}

=== turquoisehealth/provider-price-transparency-guide/examples/standardcharges/standardcharges-sample.json
{
  "reporting_entity_name": "St. Bonaventure Hospital",
  "reporting_entity_medicare_id": "123456",
  "last_update_on": "2020-01-01",
  "standardcharges": [
    {
      "description": "Arthroplasty, knee condyle and plateau, medial and lateral compartments",
      "billing_code_type": "CPT",
      "billing_code_type_version": "2020",
      "billing_code": "27447",
      "billing_code_modifier": "LT",
      "billing_class": "facility",
      "account_base_class": "outpatient",
      "revenue_code": 360,
      "gross_charge": 300.0,
      "cash_rate": 121.11,
      "minimum_negotiated_rate": 120.45,
      "maximum_negotiated_rate": 121.11,
      "negotiated_rates": [
        {
          "payer_name": "Insurance West",
          "plan_name": "Insurance West PPO",
          "negotiated_rate": 123.45,
          "expiration_date": "2022-01-01"
        },
        {
          "payer_name": "Insurance West",
          "plan_name": "Insurance West HMO",
          "negotiated_rate": 120.45,
          "expiration_date": "2022-01-01"
        }
      ]
    },
    {
      "description": "Under Repair, Revision, and/or Reconstruction Procedures on the Femur (Thigh Region) and Knee Joint",
      "billing_code_type": "CPT",
      "billing_code_type_version": "2020",
      "billing_code": "27448",
      "billing_class": "facility",
      "account_base_class": "outpatient",
      "revenue_code": 360,
      "gross_charge": 20000.0,
      "cash_rate": 10000.0,
      "minimum_negotiated_rate": 9881.45,
      "maximum_negotiated_rate": 12003.45,
      "negotiated_rates": [
        {
          "payer_name": "Insurance West",
          "plan_name": "Insurance West PPO",
          "negotiated_rate": 12003.45,
          "expiration_date": "2022-01-01"
        },
        {
          "payer_name": "Insurance West",
          "plan_name": "Insurance West HMO",
          "negotiated_rate": 9881.45,
          "expiration_date": "2022-01-01"
        }
      ]
    }
  ]
}
